#!/bin/sh
#export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
sqlplus64 "username/password@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.scs.ryerson.ca) (Port=1521))(CONNECT_DATA=(SID=orcl)))" <<EOF
DROP TABLE access_movie CASCADE CONSTRAINTS;
DROP TABLE customer_transaction CASCADE CONSTRAINTS;
DROP TABLE genre_of CASCADE CONSTRAINTS;
DROP TABLE appear_in CASCADE CONSTRAINTS;
DROP TABLE produces CASCADE CONSTRAINTS;
DROP TABLE movie_library CASCADE CONSTRAINTS;
DROP TABLE genre CASCADE CONSTRAINTS;
DROP TABLE production CASCADE CONSTRAINTS;
DROP TABLE director CASCADE CONSTRAINTS;
DROP TABLE actor CASCADE CONSTRAINTS;
DROP TABLE employee CASCADE CONSTRAINTS;
DROP TABLE department CASCADE CONSTRAINTS;
DROP TABLE customer CASCADE CONSTRAINTS;
DROP TABLE payment_method CASCADE CONSTRAINTS;
exit;
EOF